[workspace]
members = ["crates/sheetom-core", "crates/sheetom-native", "crates/sheetom-wasm"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT"
rust-version = "1.88"

[patch.crates-io]
cssparser = { path = "vendor/cssparser" }
cssparser-color = { path = "vendor/cssparser/color" }
cssparser-macros = { path = "vendor/cssparser/macros" }
lightningcss = { path = "vendor/lightningcss" }
lightningcss-derive = { path = "vendor/lightningcss/derive" }
parcel_selectors = { path = "vendor/lightningcss/selectors" }

[profile.release]
codegen-units = 1
lto = true
panic = "unwind"
strip = "symbols"

[profile.wasm-release]
inherits = "release"
opt-level = "z"
