/* auto-generated by NAPI-RS */
/* eslint-disable */
/**
 * Exercises the native string boundary while the engine runs in shadow mode.
 *
 * This deliberately accepts and returns owned strings. Lightning CSS AST nodes
 * never cross Node-API and therefore cannot be deserialized back into Rust.
 */
export declare function canonicalizeDeclarationBlock(source: string): string

/** Identifies the exact parser baseline compiled into the native addon. */
export declare function nativeEngineRevision(): string
