/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class NativeDeclarationState {
  constructor(context?: string | undefined | null)
  get length(): number
  item(index: number): string
  getPropertyValue(name: string): string
  getPropertyPriority(name: string): string
  setProperty(name: string, value: string, priority: string): string
  removeProperty(name: string): string
  serializeLonghands(): string
  replaceCssText(source: string): void
  clear(): void
  get cssText(): string
  serializeSafe(): string
  serializeFormatted(safe: boolean, indent: string, separator: string): string
}

/**
 * Exercises the native string boundary while the engine runs in shadow mode.
 *
 * This deliberately accepts and returns owned strings. Lightning CSS AST nodes
 * never cross Node-API and therefore cannot be deserialized back into Rust.
 */
export declare function canonicalizeDeclarationBlock(source: string): string

/** Identifies the exact parser baseline compiled into the native addon. */
export declare function nativeEngineRevision(): string

export declare function normalizeMedia(source: string): string

export declare function normalizeSelector(source: string): string

export declare function normalizeSupports(source: string): string

export declare function parseContainerPreludeJson(source: string): string

export declare function parseCounterStyleDescriptorsJson(source: string): string

export declare function parseCounterStyleDescriptorValue(name: string, value: string): string | null

export declare function parseCounterStyleNameJson(source: string): string | null

/** Parses exactly one rule with browser-style declaration recovery. */
export declare function parseRecoveredRuleTreeJson(source: string): string

/** Parses exactly one rule and returns an owned, parser-independent JSON DTO. */
export declare function parseRuleTreeJson(source: string): string

export declare function parseScopePreludeJson(source: string): string

/** Parses a stylesheet and returns owned, parser-independent JSON DTOs. */
export declare function parseStylesheetTreeJson(source: string, errorRecovery: boolean): string

/** Scans exact top-level CSS rule source without exposing native parser nodes. */
export declare function scanTopLevelRulesJson(source: string): string

export declare function serializeFontFamilyValue(value: string): string

export declare function serializeIdentifierValue(value: string): string
