import assert from "node:assert/strict";
import { access, readFile, readdir, writeFile } from "node:fs/promises";
import path from "node:path";

interface AdrEntry {
  id: number;
  paddedId: string;
  file: string;
  title: string;
  status: string;
}

const root = process.cwd();
const adrDirectory = path.join(root, "docs", "adr");
const indexPath = path.join(adrDirectory, "README.md");
const record = process.argv.includes("--write");

async function pathExists(file: string): Promise<boolean> {
  try {
    await access(file);
    return true;
  } catch {
    return false;
  }
}

function parseStatus(source: string, file: string, id: number): string {
  const frontmatter = source.match(/^---\n([\s\S]*?)\n---\n/u)?.[1];
  if (!frontmatter) {
    assert.ok(id < 177, `${file} must declare an explicit ADR status`);
    return "accepted";
  }

  const status = frontmatter.match(/^status:\s*(.+)$/mu)?.[1]?.trim();
  if (!status) throw new Error(`${file} frontmatter must declare a status`);
  assert.match(
    status,
    /^(accepted|superseded(?: by ADR(?:-| )?\d{4})?)$/u,
    `${file} has an unsupported ADR status: ${status}`,
  );
  return status;
}

function parseTitle(source: string, paddedId: string, file: string): string {
  const heading = source.match(/^#\s+(.+)$/mu)?.[1]?.trim();
  if (!heading) throw new Error(`${file} must have a level-one heading`);

  const numbered = heading.match(/^ADR\s+(\d{4}):\s+(.+)$/u);
  if (!numbered) return heading;

  const [numberedId, title] = numbered.slice(1);
  assert.equal(numberedId, paddedId, `${file} heading uses the wrong ADR number`);
  if (!title) throw new Error(`${file} must have a title after its ADR number`);
  return title;
}

async function readAdrs(): Promise<AdrEntry[]> {
  const filenames = (await readdir(adrDirectory))
    .filter(file => file.endsWith(".md") && file !== "README.md")
    .sort();
  const entries: AdrEntry[] = [];

  for (const file of filenames) {
    const match = file.match(/^(\d{4})-[a-z0-9]+(?:-[a-z0-9]+)*\.md$/u);
    if (!match) throw new Error(`ADR filename must be NNNN-kebab-case.md: ${file}`);
    const paddedId = match[1];
    if (!paddedId) throw new Error(`ADR filename must start with an ID: ${file}`);
    const source = await readFile(path.join(adrDirectory, file), "utf8");
    const id = Number.parseInt(paddedId, 10);
    entries.push({
      id,
      paddedId,
      file,
      title: parseTitle(source, paddedId, file),
      status: parseStatus(source, file, id),
    });
  }

  entries.sort((left, right) => left.id - right.id);
  for (const [index, entry] of entries.entries()) {
    assert.equal(
      entry.id,
      index + 1,
      `ADR IDs must be unique and contiguous; expected ${String(index + 1).padStart(4, "0")}, found ${entry.paddedId}`,
    );
  }
  return entries;
}

function renderIndex(entries: readonly AdrEntry[]): string {
  const rows = entries.map(entry =>
    `| ${entry.paddedId} | [${entry.title}](./${entry.file}) | ${entry.status} |`
  );
  return [
    "# Architecture decision records",
    "",
    "This index is generated by `scripts/check-documentation.ts`. Run",
    "`node scripts/check-documentation.ts --write` after adding or renumbering an ADR.",
    "",
    "ADRs without frontmatter predate explicit status metadata and are treated as",
    "accepted. New ADRs should declare `status: accepted` or a supported",
    "`superseded` status in YAML frontmatter.",
    "",
    "| ID | Decision | Status |",
    "| --- | --- | --- |",
    ...rows,
    "",
  ].join("\n");
}

async function validateDocumentationShape(): Promise<void> {
  for (const required of [
    "README.md",
    "CONTRIBUTING.md",
    "SECURITY.md",
    "docs/api.md",
    "docs/architecture.md",
    "docs/compatibility.md",
    "docs/releasing.md",
  ]) {
    assert.equal(await pathExists(path.join(root, required)), true, `missing ${required}`);
  }

  for (const obsolete of [
    "CONTEXT.md",
    "docs/rc6-plan.md",
    "docs/rc6-typed-value-engine-plan.md",
  ]) {
    assert.equal(await pathExists(path.join(root, obsolete)), false, `obsolete ${obsolete} remains`);
  }
}

async function validateLocalLinks(files: readonly string[]): Promise<void> {
  for (const file of files) {
    const absoluteFile = path.join(root, file);
    const source = await readFile(absoluteFile, "utf8");
    const links = source.matchAll(/(?<!!)\[[^\]]+\]\(([^)]+)\)/gu);

    for (const match of links) {
      const href = match[1];
      if (!href) continue;
      const target = href.replace(/^<|>$/gu, "").split("#", 1)[0];
      if (!target || /^(?:[a-z]+:|\/)/iu.test(target)) continue;
      const resolved = path.resolve(path.dirname(absoluteFile), target);
      assert.equal(await pathExists(resolved), true, `${file} links to missing ${target}`);
    }
  }
}

await validateDocumentationShape();
const entries = await readAdrs();
const expectedIndex = renderIndex(entries);

if (record) {
  await writeFile(indexPath, expectedIndex);
} else {
  assert.equal(
    await readFile(indexPath, "utf8"),
    expectedIndex,
    "docs/adr/README.md is stale; run node scripts/check-documentation.ts --write",
  );
}

await validateLocalLinks([
  "README.md",
  "CONTRIBUTING.md",
  "SECURITY.md",
  "docs/api.md",
  "docs/architecture.md",
  "docs/compatibility.md",
  "docs/releasing.md",
  "docs/adr/README.md",
]);

console.log(`Verified ${entries.length} ordered ADRs and project documentation links.`);
