[package]
name = "sheetom-core"
version = "0.1.0-rc.7"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
cssparser = "=0.37.0"
lightningcss = { version = "=1.0.0-alpha.72", default-features = false, features = ["into_owned"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.149"
svgtypes = "=0.16.1"

[dev-dependencies]
