[package]
name = "sheetom-core"
version = "0.1.1"
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish = false

[dependencies]
cssparser = "=0.37.0"
lightningcss = { version = "=1.0.0-alpha.72", default-features = false, features = ["into_owned"] }
phf = { version = "=0.13.1", features = ["macros"] }
serde = { version = "=1.0.229", features = ["derive"] }
serde_json = "=1.0.149"
smallvec = "=1.15.2"
svgtypes = "=0.16.1"

[dev-dependencies]
