// Generated by npm run generate:properties. Do not edit manually.
export const chromiumPropertyBaseline = "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/151.0.7922.34 Safari/537.36";

export const chromiumSupportedProperties = new Set([
  "-webkit-align-content",
  "-webkit-align-items",
  "-webkit-align-self",
  "-webkit-animation",
  "-webkit-animation-delay",
  "-webkit-animation-direction",
  "-webkit-animation-duration",
  "-webkit-animation-fill-mode",
  "-webkit-animation-iteration-count",
  "-webkit-animation-name",
  "-webkit-animation-play-state",
  "-webkit-animation-timing-function",
  "-webkit-app-region",
  "-webkit-appearance",
  "-webkit-backface-visibility",
  "-webkit-background-clip",
  "-webkit-background-origin",
  "-webkit-background-size",
  "-webkit-border-after",
  "-webkit-border-after-color",
  "-webkit-border-after-style",
  "-webkit-border-after-width",
  "-webkit-border-before",
  "-webkit-border-before-color",
  "-webkit-border-before-style",
  "-webkit-border-before-width",
  "-webkit-border-bottom-left-radius",
  "-webkit-border-bottom-right-radius",
  "-webkit-border-end",
  "-webkit-border-end-color",
  "-webkit-border-end-style",
  "-webkit-border-end-width",
  "-webkit-border-horizontal-spacing",
  "-webkit-border-image",
  "-webkit-border-radius",
  "-webkit-border-start",
  "-webkit-border-start-color",
  "-webkit-border-start-style",
  "-webkit-border-start-width",
  "-webkit-border-top-left-radius",
  "-webkit-border-top-right-radius",
  "-webkit-border-vertical-spacing",
  "-webkit-box-align",
  "-webkit-box-decoration-break",
  "-webkit-box-direction",
  "-webkit-box-flex",
  "-webkit-box-ordinal-group",
  "-webkit-box-orient",
  "-webkit-box-pack",
  "-webkit-box-reflect",
  "-webkit-box-shadow",
  "-webkit-box-sizing",
  "-webkit-clip-path",
  "-webkit-column-break-after",
  "-webkit-column-break-before",
  "-webkit-column-break-inside",
  "-webkit-column-count",
  "-webkit-column-gap",
  "-webkit-column-rule",
  "-webkit-column-rule-color",
  "-webkit-column-rule-style",
  "-webkit-column-rule-width",
  "-webkit-column-span",
  "-webkit-column-width",
  "-webkit-columns",
  "-webkit-filter",
  "-webkit-flex",
  "-webkit-flex-basis",
  "-webkit-flex-direction",
  "-webkit-flex-flow",
  "-webkit-flex-grow",
  "-webkit-flex-shrink",
  "-webkit-flex-wrap",
  "-webkit-font-feature-settings",
  "-webkit-font-smoothing",
  "-webkit-hyphenate-character",
  "-webkit-justify-content",
  "-webkit-line-break",
  "-webkit-line-clamp",
  "-webkit-locale",
  "-webkit-logical-height",
  "-webkit-logical-width",
  "-webkit-margin-after",
  "-webkit-margin-before",
  "-webkit-margin-end",
  "-webkit-margin-start",
  "-webkit-mask",
  "-webkit-mask-box-image",
  "-webkit-mask-box-image-outset",
  "-webkit-mask-box-image-repeat",
  "-webkit-mask-box-image-slice",
  "-webkit-mask-box-image-source",
  "-webkit-mask-box-image-width",
  "-webkit-mask-clip",
  "-webkit-mask-composite",
  "-webkit-mask-image",
  "-webkit-mask-origin",
  "-webkit-mask-position",
  "-webkit-mask-position-x",
  "-webkit-mask-position-y",
  "-webkit-mask-repeat",
  "-webkit-mask-size",
  "-webkit-max-logical-height",
  "-webkit-max-logical-width",
  "-webkit-min-logical-height",
  "-webkit-min-logical-width",
  "-webkit-opacity",
  "-webkit-order",
  "-webkit-padding-after",
  "-webkit-padding-before",
  "-webkit-padding-end",
  "-webkit-padding-start",
  "-webkit-perspective",
  "-webkit-perspective-origin",
  "-webkit-perspective-origin-x",
  "-webkit-perspective-origin-y",
  "-webkit-print-color-adjust",
  "-webkit-rtl-ordering",
  "-webkit-ruby-position",
  "-webkit-shape-image-threshold",
  "-webkit-shape-margin",
  "-webkit-shape-outside",
  "-webkit-tap-highlight-color",
  "-webkit-text-combine",
  "-webkit-text-decorations-in-effect",
  "-webkit-text-emphasis",
  "-webkit-text-emphasis-color",
  "-webkit-text-emphasis-position",
  "-webkit-text-emphasis-style",
  "-webkit-text-fill-color",
  "-webkit-text-orientation",
  "-webkit-text-security",
  "-webkit-text-size-adjust",
  "-webkit-text-stroke",
  "-webkit-text-stroke-color",
  "-webkit-text-stroke-width",
  "-webkit-transform",
  "-webkit-transform-origin",
  "-webkit-transform-origin-x",
  "-webkit-transform-origin-y",
  "-webkit-transform-origin-z",
  "-webkit-transform-style",
  "-webkit-transition",
  "-webkit-transition-delay",
  "-webkit-transition-duration",
  "-webkit-transition-property",
  "-webkit-transition-timing-function",
  "-webkit-user-drag",
  "-webkit-user-modify",
  "-webkit-user-select",
  "-webkit-writing-mode",
  "accent-color",
  "align-content",
  "align-items",
  "align-self",
  "alignment-baseline",
  "all",
  "anchor-name",
  "anchor-scope",
  "animation",
  "animation-composition",
  "animation-delay",
  "animation-direction",
  "animation-duration",
  "animation-fill-mode",
  "animation-iteration-count",
  "animation-name",
  "animation-play-state",
  "animation-range",
  "animation-range-end",
  "animation-range-start",
  "animation-timeline",
  "animation-timing-function",
  "animation-trigger",
  "app-region",
  "appearance",
  "aspect-ratio",
  "backdrop-filter",
  "backface-visibility",
  "background",
  "background-attachment",
  "background-blend-mode",
  "background-clip",
  "background-color",
  "background-image",
  "background-origin",
  "background-position",
  "background-position-x",
  "background-position-y",
  "background-repeat",
  "background-size",
  "baseline-shift",
  "baseline-source",
  "block-size",
  "border",
  "border-block",
  "border-block-color",
  "border-block-end",
  "border-block-end-color",
  "border-block-end-style",
  "border-block-end-width",
  "border-block-start",
  "border-block-start-color",
  "border-block-start-style",
  "border-block-start-width",
  "border-block-style",
  "border-block-width",
  "border-bottom",
  "border-bottom-color",
  "border-bottom-left-radius",
  "border-bottom-right-radius",
  "border-bottom-style",
  "border-bottom-width",
  "border-collapse",
  "border-color",
  "border-end-end-radius",
  "border-end-start-radius",
  "border-image",
  "border-image-outset",
  "border-image-repeat",
  "border-image-slice",
  "border-image-source",
  "border-image-width",
  "border-inline",
  "border-inline-color",
  "border-inline-end",
  "border-inline-end-color",
  "border-inline-end-style",
  "border-inline-end-width",
  "border-inline-start",
  "border-inline-start-color",
  "border-inline-start-style",
  "border-inline-start-width",
  "border-inline-style",
  "border-inline-width",
  "border-left",
  "border-left-color",
  "border-left-style",
  "border-left-width",
  "border-radius",
  "border-right",
  "border-right-color",
  "border-right-style",
  "border-right-width",
  "border-shape",
  "border-spacing",
  "border-start-end-radius",
  "border-start-start-radius",
  "border-style",
  "border-top",
  "border-top-color",
  "border-top-left-radius",
  "border-top-right-radius",
  "border-top-style",
  "border-top-width",
  "border-width",
  "bottom",
  "box-decoration-break",
  "box-shadow",
  "box-sizing",
  "break-after",
  "break-before",
  "break-inside",
  "buffered-rendering",
  "caption-side",
  "caret-animation",
  "caret-color",
  "caret-shape",
  "clear",
  "clip",
  "clip-path",
  "clip-rule",
  "color",
  "color-interpolation",
  "color-interpolation-filters",
  "color-rendering",
  "color-scheme",
  "column-count",
  "column-fill",
  "column-gap",
  "column-height",
  "column-rule",
  "column-rule-break",
  "column-rule-color",
  "column-rule-inset",
  "column-rule-inset-cap",
  "column-rule-inset-cap-end",
  "column-rule-inset-cap-start",
  "column-rule-inset-end",
  "column-rule-inset-junction",
  "column-rule-inset-junction-end",
  "column-rule-inset-junction-start",
  "column-rule-inset-start",
  "column-rule-style",
  "column-rule-visibility-items",
  "column-rule-width",
  "column-span",
  "column-width",
  "column-wrap",
  "columns",
  "contain",
  "contain-intrinsic-block-size",
  "contain-intrinsic-height",
  "contain-intrinsic-inline-size",
  "contain-intrinsic-size",
  "contain-intrinsic-width",
  "container",
  "container-name",
  "container-type",
  "content",
  "content-visibility",
  "corner-block-end-shape",
  "corner-block-start-shape",
  "corner-bottom-left-shape",
  "corner-bottom-right-shape",
  "corner-bottom-shape",
  "corner-end-end-shape",
  "corner-end-start-shape",
  "corner-inline-end-shape",
  "corner-inline-start-shape",
  "corner-left-shape",
  "corner-right-shape",
  "corner-shape",
  "corner-start-end-shape",
  "corner-start-start-shape",
  "corner-top-left-shape",
  "corner-top-right-shape",
  "corner-top-shape",
  "counter-increment",
  "counter-reset",
  "counter-set",
  "cursor",
  "cx",
  "cy",
  "d",
  "direction",
  "display",
  "dominant-baseline",
  "dynamic-range-limit",
  "empty-cells",
  "field-sizing",
  "fill",
  "fill-opacity",
  "fill-rule",
  "filter",
  "flex",
  "flex-basis",
  "flex-direction",
  "flex-flow",
  "flex-grow",
  "flex-line-count",
  "flex-shrink",
  "flex-wrap",
  "float",
  "flood-color",
  "flood-opacity",
  "font",
  "font-family",
  "font-feature-settings",
  "font-kerning",
  "font-language-override",
  "font-optical-sizing",
  "font-palette",
  "font-size",
  "font-size-adjust",
  "font-stretch",
  "font-style",
  "font-synthesis",
  "font-synthesis-small-caps",
  "font-synthesis-style",
  "font-synthesis-weight",
  "font-variant",
  "font-variant-alternates",
  "font-variant-caps",
  "font-variant-east-asian",
  "font-variant-emoji",
  "font-variant-ligatures",
  "font-variant-numeric",
  "font-variant-position",
  "font-variation-settings",
  "font-weight",
  "forced-color-adjust",
  "gap",
  "grid",
  "grid-area",
  "grid-auto-columns",
  "grid-auto-flow",
  "grid-auto-rows",
  "grid-column",
  "grid-column-end",
  "grid-column-gap",
  "grid-column-start",
  "grid-gap",
  "grid-row",
  "grid-row-end",
  "grid-row-gap",
  "grid-row-start",
  "grid-template",
  "grid-template-areas",
  "grid-template-columns",
  "grid-template-rows",
  "height",
  "hyphenate-character",
  "hyphenate-limit-chars",
  "hyphens",
  "image-orientation",
  "image-rendering",
  "initial-letter",
  "inline-size",
  "inset",
  "inset-block",
  "inset-block-end",
  "inset-block-start",
  "inset-inline",
  "inset-inline-end",
  "inset-inline-start",
  "interactivity",
  "interest-delay",
  "interest-delay-end",
  "interest-delay-start",
  "interpolate-size",
  "isolation",
  "justify-content",
  "justify-items",
  "justify-self",
  "left",
  "letter-spacing",
  "lighting-color",
  "line-break",
  "line-height",
  "list-style",
  "list-style-image",
  "list-style-position",
  "list-style-type",
  "margin",
  "margin-block",
  "margin-block-end",
  "margin-block-start",
  "margin-bottom",
  "margin-inline",
  "margin-inline-end",
  "margin-inline-start",
  "margin-left",
  "margin-right",
  "margin-top",
  "marker",
  "marker-end",
  "marker-mid",
  "marker-start",
  "mask",
  "mask-clip",
  "mask-composite",
  "mask-image",
  "mask-mode",
  "mask-origin",
  "mask-position",
  "mask-repeat",
  "mask-size",
  "mask-type",
  "math-depth",
  "math-shift",
  "math-style",
  "max-block-size",
  "max-height",
  "max-inline-size",
  "max-width",
  "min-block-size",
  "min-height",
  "min-inline-size",
  "min-width",
  "mix-blend-mode",
  "object-fit",
  "object-position",
  "object-view-box",
  "offset",
  "offset-anchor",
  "offset-distance",
  "offset-path",
  "offset-position",
  "offset-rotate",
  "opacity",
  "order",
  "orphans",
  "outline",
  "outline-color",
  "outline-offset",
  "outline-style",
  "outline-width",
  "overflow",
  "overflow-anchor",
  "overflow-block",
  "overflow-clip-margin",
  "overflow-inline",
  "overflow-wrap",
  "overflow-x",
  "overflow-y",
  "overlay",
  "overscroll-behavior",
  "overscroll-behavior-block",
  "overscroll-behavior-inline",
  "overscroll-behavior-x",
  "overscroll-behavior-y",
  "padding",
  "padding-block",
  "padding-block-end",
  "padding-block-start",
  "padding-bottom",
  "padding-inline",
  "padding-inline-end",
  "padding-inline-start",
  "padding-left",
  "padding-right",
  "padding-top",
  "page",
  "page-break-after",
  "page-break-before",
  "page-break-inside",
  "page-margin-safety",
  "page-orientation",
  "paint-order",
  "perspective",
  "perspective-origin",
  "place-content",
  "place-items",
  "place-self",
  "pointer-events",
  "position",
  "position-anchor",
  "position-area",
  "position-try",
  "position-try-fallbacks",
  "position-try-order",
  "position-visibility",
  "print-color-adjust",
  "quotes",
  "r",
  "reading-flow",
  "reading-order",
  "resize",
  "right",
  "rotate",
  "row-gap",
  "row-rule",
  "row-rule-break",
  "row-rule-color",
  "row-rule-inset",
  "row-rule-inset-cap",
  "row-rule-inset-cap-end",
  "row-rule-inset-cap-start",
  "row-rule-inset-end",
  "row-rule-inset-junction",
  "row-rule-inset-junction-end",
  "row-rule-inset-junction-start",
  "row-rule-inset-start",
  "row-rule-style",
  "row-rule-visibility-items",
  "row-rule-width",
  "ruby-align",
  "ruby-overhang",
  "ruby-position",
  "rule",
  "rule-break",
  "rule-color",
  "rule-inset",
  "rule-inset-cap",
  "rule-inset-end",
  "rule-inset-junction",
  "rule-inset-start",
  "rule-overlap",
  "rule-style",
  "rule-visibility-items",
  "rule-width",
  "rx",
  "ry",
  "scale",
  "scroll-behavior",
  "scroll-initial-target",
  "scroll-margin",
  "scroll-margin-block",
  "scroll-margin-block-end",
  "scroll-margin-block-start",
  "scroll-margin-bottom",
  "scroll-margin-inline",
  "scroll-margin-inline-end",
  "scroll-margin-inline-start",
  "scroll-margin-left",
  "scroll-margin-right",
  "scroll-margin-top",
  "scroll-marker-group",
  "scroll-padding",
  "scroll-padding-block",
  "scroll-padding-block-end",
  "scroll-padding-block-start",
  "scroll-padding-bottom",
  "scroll-padding-inline",
  "scroll-padding-inline-end",
  "scroll-padding-inline-start",
  "scroll-padding-left",
  "scroll-padding-right",
  "scroll-padding-top",
  "scroll-snap-align",
  "scroll-snap-stop",
  "scroll-snap-type",
  "scroll-target-group",
  "scroll-timeline",
  "scroll-timeline-axis",
  "scroll-timeline-name",
  "scrollbar-color",
  "scrollbar-gutter",
  "scrollbar-width",
  "shape-image-threshold",
  "shape-margin",
  "shape-outside",
  "shape-rendering",
  "size",
  "speak",
  "stop-color",
  "stop-opacity",
  "stroke",
  "stroke-dasharray",
  "stroke-dashoffset",
  "stroke-linecap",
  "stroke-linejoin",
  "stroke-miterlimit",
  "stroke-opacity",
  "stroke-width",
  "tab-size",
  "table-layout",
  "text-align",
  "text-align-last",
  "text-anchor",
  "text-autospace",
  "text-box",
  "text-box-edge",
  "text-box-trim",
  "text-combine-upright",
  "text-decoration",
  "text-decoration-color",
  "text-decoration-line",
  "text-decoration-skip-ink",
  "text-decoration-style",
  "text-decoration-thickness",
  "text-emphasis",
  "text-emphasis-color",
  "text-emphasis-position",
  "text-emphasis-style",
  "text-fit",
  "text-indent",
  "text-justify",
  "text-orientation",
  "text-overflow",
  "text-rendering",
  "text-shadow",
  "text-size-adjust",
  "text-spacing-trim",
  "text-transform",
  "text-underline-offset",
  "text-underline-position",
  "text-wrap",
  "text-wrap-mode",
  "text-wrap-style",
  "timeline-scope",
  "timeline-trigger",
  "timeline-trigger-activation-range",
  "timeline-trigger-activation-range-end",
  "timeline-trigger-activation-range-start",
  "timeline-trigger-active-range",
  "timeline-trigger-active-range-end",
  "timeline-trigger-active-range-start",
  "timeline-trigger-name",
  "timeline-trigger-source",
  "top",
  "touch-action",
  "transform",
  "transform-box",
  "transform-origin",
  "transform-style",
  "transition",
  "transition-behavior",
  "transition-delay",
  "transition-duration",
  "transition-property",
  "transition-timing-function",
  "translate",
  "trigger-scope",
  "unicode-bidi",
  "user-select",
  "vector-effect",
  "vertical-align",
  "view-timeline",
  "view-timeline-axis",
  "view-timeline-inset",
  "view-timeline-name",
  "view-transition-class",
  "view-transition-group",
  "view-transition-name",
  "view-transition-scope",
  "visibility",
  "white-space",
  "white-space-collapse",
  "widows",
  "width",
  "will-change",
  "word-break",
  "word-spacing",
  "word-wrap",
  "writing-mode",
  "x",
  "y",
  "z-index",
  "zoom"
]);

export const chromiumShorthandLonghands: Readonly<Record<string, readonly string[]>> = {
  "-webkit-align-content": [
    "align-content"
  ],
  "-webkit-align-items": [
    "align-items"
  ],
  "-webkit-align-self": [
    "align-self"
  ],
  "-webkit-animation": [
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "animation-fill-mode",
    "animation-play-state",
    "animation-name",
    "animation-timeline",
    "animation-range-start",
    "animation-range-end"
  ],
  "-webkit-animation-delay": [
    "animation-delay"
  ],
  "-webkit-animation-direction": [
    "animation-direction"
  ],
  "-webkit-animation-duration": [
    "animation-duration"
  ],
  "-webkit-animation-fill-mode": [
    "animation-fill-mode"
  ],
  "-webkit-animation-iteration-count": [
    "animation-iteration-count"
  ],
  "-webkit-animation-name": [
    "animation-name"
  ],
  "-webkit-animation-play-state": [
    "animation-play-state"
  ],
  "-webkit-animation-timing-function": [
    "animation-timing-function"
  ],
  "-webkit-app-region": [
    "app-region"
  ],
  "-webkit-appearance": [
    "appearance"
  ],
  "-webkit-backface-visibility": [
    "backface-visibility"
  ],
  "-webkit-background-clip": [
    "background-clip"
  ],
  "-webkit-background-origin": [
    "background-origin"
  ],
  "-webkit-background-size": [
    "background-size"
  ],
  "-webkit-border-after": [
    "border-block-end-width",
    "border-block-end-style",
    "border-block-end-color"
  ],
  "-webkit-border-after-color": [
    "border-block-end-color"
  ],
  "-webkit-border-after-style": [
    "border-block-end-style"
  ],
  "-webkit-border-after-width": [
    "border-block-end-width"
  ],
  "-webkit-border-before": [
    "border-block-start-width",
    "border-block-start-style",
    "border-block-start-color"
  ],
  "-webkit-border-before-color": [
    "border-block-start-color"
  ],
  "-webkit-border-before-style": [
    "border-block-start-style"
  ],
  "-webkit-border-before-width": [
    "border-block-start-width"
  ],
  "-webkit-border-bottom-left-radius": [
    "border-bottom-left-radius"
  ],
  "-webkit-border-bottom-right-radius": [
    "border-bottom-right-radius"
  ],
  "-webkit-border-end": [
    "border-inline-end-width",
    "border-inline-end-style",
    "border-inline-end-color"
  ],
  "-webkit-border-end-color": [
    "border-inline-end-color"
  ],
  "-webkit-border-end-style": [
    "border-inline-end-style"
  ],
  "-webkit-border-end-width": [
    "border-inline-end-width"
  ],
  "-webkit-border-radius": [
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius"
  ],
  "-webkit-border-start": [
    "border-inline-start-width",
    "border-inline-start-style",
    "border-inline-start-color"
  ],
  "-webkit-border-start-color": [
    "border-inline-start-color"
  ],
  "-webkit-border-start-style": [
    "border-inline-start-style"
  ],
  "-webkit-border-start-width": [
    "border-inline-start-width"
  ],
  "-webkit-border-top-left-radius": [
    "border-top-left-radius"
  ],
  "-webkit-border-top-right-radius": [
    "border-top-right-radius"
  ],
  "-webkit-box-shadow": [
    "box-shadow"
  ],
  "-webkit-box-sizing": [
    "box-sizing"
  ],
  "-webkit-clip-path": [
    "clip-path"
  ],
  "-webkit-column-break-after": [
    "break-after"
  ],
  "-webkit-column-break-before": [
    "break-before"
  ],
  "-webkit-column-break-inside": [
    "break-inside"
  ],
  "-webkit-column-count": [
    "column-count"
  ],
  "-webkit-column-gap": [
    "column-gap"
  ],
  "-webkit-column-rule": [
    "column-rule-width",
    "column-rule-style",
    "column-rule-color"
  ],
  "-webkit-column-rule-color": [
    "column-rule-color"
  ],
  "-webkit-column-rule-style": [
    "column-rule-style"
  ],
  "-webkit-column-rule-width": [
    "column-rule-width"
  ],
  "-webkit-column-span": [
    "column-span"
  ],
  "-webkit-column-width": [
    "column-width"
  ],
  "-webkit-columns": [
    "column-width",
    "column-count",
    "column-height",
    "column-wrap"
  ],
  "-webkit-filter": [
    "filter"
  ],
  "-webkit-flex": [
    "flex-grow",
    "flex-shrink",
    "flex-basis"
  ],
  "-webkit-flex-basis": [
    "flex-basis"
  ],
  "-webkit-flex-direction": [
    "flex-direction"
  ],
  "-webkit-flex-flow": [
    "flex-direction",
    "flex-wrap"
  ],
  "-webkit-flex-grow": [
    "flex-grow"
  ],
  "-webkit-flex-shrink": [
    "flex-shrink"
  ],
  "-webkit-flex-wrap": [
    "flex-wrap"
  ],
  "-webkit-font-feature-settings": [
    "font-feature-settings"
  ],
  "-webkit-hyphenate-character": [
    "hyphenate-character"
  ],
  "-webkit-justify-content": [
    "justify-content"
  ],
  "-webkit-logical-height": [
    "block-size"
  ],
  "-webkit-logical-width": [
    "inline-size"
  ],
  "-webkit-margin-after": [
    "margin-block-end"
  ],
  "-webkit-margin-before": [
    "margin-block-start"
  ],
  "-webkit-margin-end": [
    "margin-inline-end"
  ],
  "-webkit-margin-start": [
    "margin-inline-start"
  ],
  "-webkit-mask": [
    "mask-image",
    "-webkit-mask-position-x",
    "-webkit-mask-position-y",
    "mask-size",
    "mask-repeat",
    "mask-origin",
    "mask-clip",
    "mask-composite",
    "mask-mode"
  ],
  "-webkit-mask-box-image": [
    "-webkit-mask-box-image-source",
    "-webkit-mask-box-image-slice",
    "-webkit-mask-box-image-width",
    "-webkit-mask-box-image-outset",
    "-webkit-mask-box-image-repeat"
  ],
  "-webkit-mask-clip": [
    "mask-clip"
  ],
  "-webkit-mask-composite": [
    "mask-composite"
  ],
  "-webkit-mask-image": [
    "mask-image"
  ],
  "-webkit-mask-origin": [
    "mask-origin"
  ],
  "-webkit-mask-position": [
    "-webkit-mask-position-x",
    "-webkit-mask-position-y"
  ],
  "-webkit-mask-repeat": [
    "mask-repeat"
  ],
  "-webkit-mask-size": [
    "mask-size"
  ],
  "-webkit-max-logical-height": [
    "max-block-size"
  ],
  "-webkit-max-logical-width": [
    "max-inline-size"
  ],
  "-webkit-min-logical-height": [
    "min-block-size"
  ],
  "-webkit-min-logical-width": [
    "min-inline-size"
  ],
  "-webkit-opacity": [
    "opacity"
  ],
  "-webkit-order": [
    "order"
  ],
  "-webkit-padding-after": [
    "padding-block-end"
  ],
  "-webkit-padding-before": [
    "padding-block-start"
  ],
  "-webkit-padding-end": [
    "padding-inline-end"
  ],
  "-webkit-padding-start": [
    "padding-inline-start"
  ],
  "-webkit-perspective": [
    "perspective"
  ],
  "-webkit-perspective-origin": [
    "perspective-origin"
  ],
  "-webkit-print-color-adjust": [
    "print-color-adjust"
  ],
  "-webkit-shape-image-threshold": [
    "shape-image-threshold"
  ],
  "-webkit-shape-margin": [
    "shape-margin"
  ],
  "-webkit-shape-outside": [
    "shape-outside"
  ],
  "-webkit-text-emphasis": [
    "text-emphasis-style",
    "text-emphasis-color"
  ],
  "-webkit-text-emphasis-color": [
    "text-emphasis-color"
  ],
  "-webkit-text-emphasis-position": [
    "text-emphasis-position"
  ],
  "-webkit-text-emphasis-style": [
    "text-emphasis-style"
  ],
  "-webkit-text-size-adjust": [
    "text-size-adjust"
  ],
  "-webkit-text-stroke": [
    "-webkit-text-stroke-width",
    "-webkit-text-stroke-color"
  ],
  "-webkit-transform": [
    "transform"
  ],
  "-webkit-transform-origin": [
    "transform-origin"
  ],
  "-webkit-transform-style": [
    "transform-style"
  ],
  "-webkit-transition": [
    "transition-property",
    "transition-duration",
    "transition-timing-function",
    "transition-delay",
    "transition-behavior"
  ],
  "-webkit-transition-delay": [
    "transition-delay"
  ],
  "-webkit-transition-duration": [
    "transition-duration"
  ],
  "-webkit-transition-property": [
    "transition-property"
  ],
  "-webkit-transition-timing-function": [
    "transition-timing-function"
  ],
  "-webkit-user-select": [
    "user-select"
  ],
  "animation": [
    "animation-duration",
    "animation-timing-function",
    "animation-delay",
    "animation-iteration-count",
    "animation-direction",
    "animation-fill-mode",
    "animation-play-state",
    "animation-name",
    "animation-timeline",
    "animation-range-start",
    "animation-range-end"
  ],
  "animation-range": [
    "animation-range-start",
    "animation-range-end"
  ],
  "background": [
    "background-image",
    "background-position-x",
    "background-position-y",
    "background-size",
    "background-repeat",
    "background-attachment",
    "background-origin",
    "background-clip",
    "background-color"
  ],
  "background-position": [
    "background-position-x",
    "background-position-y"
  ],
  "border": [
    "border-top-color",
    "border-top-style",
    "border-top-width",
    "border-right-color",
    "border-right-style",
    "border-right-width",
    "border-bottom-color",
    "border-bottom-style",
    "border-bottom-width",
    "border-left-color",
    "border-left-style",
    "border-left-width",
    "border-image-source",
    "border-image-slice",
    "border-image-width",
    "border-image-outset",
    "border-image-repeat"
  ],
  "border-block": [
    "border-block-start-color",
    "border-block-start-style",
    "border-block-start-width",
    "border-block-end-color",
    "border-block-end-style",
    "border-block-end-width"
  ],
  "border-block-color": [
    "border-block-start-color",
    "border-block-end-color"
  ],
  "border-block-end": [
    "border-block-end-width",
    "border-block-end-style",
    "border-block-end-color"
  ],
  "border-block-start": [
    "border-block-start-width",
    "border-block-start-style",
    "border-block-start-color"
  ],
  "border-block-style": [
    "border-block-start-style",
    "border-block-end-style"
  ],
  "border-block-width": [
    "border-block-start-width",
    "border-block-end-width"
  ],
  "border-bottom": [
    "border-bottom-width",
    "border-bottom-style",
    "border-bottom-color"
  ],
  "border-color": [
    "border-top-color",
    "border-right-color",
    "border-bottom-color",
    "border-left-color"
  ],
  "border-image": [
    "border-image-source",
    "border-image-slice",
    "border-image-width",
    "border-image-outset",
    "border-image-repeat"
  ],
  "border-inline": [
    "border-inline-start-color",
    "border-inline-start-style",
    "border-inline-start-width",
    "border-inline-end-color",
    "border-inline-end-style",
    "border-inline-end-width"
  ],
  "border-inline-color": [
    "border-inline-start-color",
    "border-inline-end-color"
  ],
  "border-inline-end": [
    "border-inline-end-width",
    "border-inline-end-style",
    "border-inline-end-color"
  ],
  "border-inline-start": [
    "border-inline-start-width",
    "border-inline-start-style",
    "border-inline-start-color"
  ],
  "border-inline-style": [
    "border-inline-start-style",
    "border-inline-end-style"
  ],
  "border-inline-width": [
    "border-inline-start-width",
    "border-inline-end-width"
  ],
  "border-left": [
    "border-left-width",
    "border-left-style",
    "border-left-color"
  ],
  "border-radius": [
    "border-top-left-radius",
    "border-top-right-radius",
    "border-bottom-right-radius",
    "border-bottom-left-radius"
  ],
  "border-right": [
    "border-right-width",
    "border-right-style",
    "border-right-color"
  ],
  "border-spacing": [
    "-webkit-border-horizontal-spacing",
    "-webkit-border-vertical-spacing"
  ],
  "border-style": [
    "border-top-style",
    "border-right-style",
    "border-bottom-style",
    "border-left-style"
  ],
  "border-top": [
    "border-top-width",
    "border-top-style",
    "border-top-color"
  ],
  "border-width": [
    "border-top-width",
    "border-right-width",
    "border-bottom-width",
    "border-left-width"
  ],
  "column-rule": [
    "column-rule-width",
    "column-rule-style",
    "column-rule-color"
  ],
  "column-rule-inset": [
    "column-rule-inset-cap-start",
    "column-rule-inset-cap-end",
    "column-rule-inset-junction-start",
    "column-rule-inset-junction-end"
  ],
  "column-rule-inset-cap": [
    "column-rule-inset-cap-start",
    "column-rule-inset-cap-end"
  ],
  "column-rule-inset-end": [
    "column-rule-inset-cap-end",
    "column-rule-inset-junction-end"
  ],
  "column-rule-inset-junction": [
    "column-rule-inset-junction-start",
    "column-rule-inset-junction-end"
  ],
  "column-rule-inset-start": [
    "column-rule-inset-cap-start",
    "column-rule-inset-junction-start"
  ],
  "columns": [
    "column-width",
    "column-count",
    "column-height",
    "column-wrap"
  ],
  "contain-intrinsic-size": [
    "contain-intrinsic-width",
    "contain-intrinsic-height"
  ],
  "container": [
    "container-name",
    "container-type"
  ],
  "corner-block-end-shape": [
    "corner-end-start-shape",
    "corner-end-end-shape"
  ],
  "corner-block-start-shape": [
    "corner-start-start-shape",
    "corner-start-end-shape"
  ],
  "corner-bottom-shape": [
    "corner-bottom-left-shape",
    "corner-bottom-right-shape"
  ],
  "corner-inline-end-shape": [
    "corner-start-end-shape",
    "corner-end-end-shape"
  ],
  "corner-inline-start-shape": [
    "corner-start-start-shape",
    "corner-end-start-shape"
  ],
  "corner-left-shape": [
    "corner-top-left-shape",
    "corner-bottom-left-shape"
  ],
  "corner-right-shape": [
    "corner-top-right-shape",
    "corner-bottom-right-shape"
  ],
  "corner-shape": [
    "corner-top-left-shape",
    "corner-top-right-shape",
    "corner-bottom-right-shape",
    "corner-bottom-left-shape"
  ],
  "corner-top-shape": [
    "corner-top-left-shape",
    "corner-top-right-shape"
  ],
  "flex": [
    "flex-grow",
    "flex-shrink",
    "flex-basis"
  ],
  "flex-flow": [
    "flex-direction",
    "flex-wrap"
  ],
  "font": [
    "font-style",
    "font-variant-ligatures",
    "font-variant-caps",
    "font-variant-numeric",
    "font-variant-east-asian",
    "font-variant-alternates",
    "font-variant-position",
    "font-variant-emoji",
    "font-weight",
    "font-stretch",
    "font-size",
    "line-height",
    "font-family",
    "font-optical-sizing",
    "font-size-adjust",
    "font-kerning",
    "font-feature-settings",
    "font-variation-settings",
    "font-language-override"
  ],
  "font-synthesis": [
    "font-synthesis-weight",
    "font-synthesis-style",
    "font-synthesis-small-caps"
  ],
  "font-variant": [
    "font-variant-ligatures",
    "font-variant-caps",
    "font-variant-alternates",
    "font-variant-numeric",
    "font-variant-east-asian",
    "font-variant-position",
    "font-variant-emoji"
  ],
  "gap": [
    "row-gap",
    "column-gap"
  ],
  "grid": [
    "grid-template-rows",
    "grid-template-columns",
    "grid-template-areas",
    "grid-auto-flow",
    "grid-auto-rows",
    "grid-auto-columns"
  ],
  "grid-area": [
    "grid-row-start",
    "grid-column-start",
    "grid-row-end",
    "grid-column-end"
  ],
  "grid-column": [
    "grid-column-start",
    "grid-column-end"
  ],
  "grid-column-gap": [
    "column-gap"
  ],
  "grid-gap": [
    "row-gap",
    "column-gap"
  ],
  "grid-row": [
    "grid-row-start",
    "grid-row-end"
  ],
  "grid-row-gap": [
    "row-gap"
  ],
  "grid-template": [
    "grid-template-rows",
    "grid-template-columns",
    "grid-template-areas"
  ],
  "inset": [
    "top",
    "right",
    "bottom",
    "left"
  ],
  "inset-block": [
    "inset-block-start",
    "inset-block-end"
  ],
  "inset-inline": [
    "inset-inline-start",
    "inset-inline-end"
  ],
  "interest-delay": [
    "interest-delay-start",
    "interest-delay-end"
  ],
  "list-style": [
    "list-style-position",
    "list-style-image",
    "list-style-type"
  ],
  "margin": [
    "margin-top",
    "margin-right",
    "margin-bottom",
    "margin-left"
  ],
  "margin-block": [
    "margin-block-start",
    "margin-block-end"
  ],
  "margin-inline": [
    "margin-inline-start",
    "margin-inline-end"
  ],
  "marker": [
    "marker-start",
    "marker-mid",
    "marker-end"
  ],
  "mask": [
    "mask-image",
    "-webkit-mask-position-x",
    "-webkit-mask-position-y",
    "mask-size",
    "mask-repeat",
    "mask-origin",
    "mask-clip",
    "mask-composite",
    "mask-mode"
  ],
  "mask-position": [
    "-webkit-mask-position-x",
    "-webkit-mask-position-y"
  ],
  "offset": [
    "offset-position",
    "offset-path",
    "offset-distance",
    "offset-rotate",
    "offset-anchor"
  ],
  "outline": [
    "outline-color",
    "outline-style",
    "outline-width"
  ],
  "overflow": [
    "overflow-x",
    "overflow-y"
  ],
  "overscroll-behavior": [
    "overscroll-behavior-x",
    "overscroll-behavior-y"
  ],
  "padding": [
    "padding-top",
    "padding-right",
    "padding-bottom",
    "padding-left"
  ],
  "padding-block": [
    "padding-block-start",
    "padding-block-end"
  ],
  "padding-inline": [
    "padding-inline-start",
    "padding-inline-end"
  ],
  "page-break-after": [
    "break-after"
  ],
  "page-break-before": [
    "break-before"
  ],
  "page-break-inside": [
    "break-inside"
  ],
  "place-content": [
    "align-content",
    "justify-content"
  ],
  "place-items": [
    "align-items",
    "justify-items"
  ],
  "place-self": [
    "align-self",
    "justify-self"
  ],
  "position-try": [
    "position-try-order",
    "position-try-fallbacks"
  ],
  "row-rule": [
    "row-rule-width",
    "row-rule-style",
    "row-rule-color"
  ],
  "row-rule-inset": [
    "row-rule-inset-cap-start",
    "row-rule-inset-cap-end",
    "row-rule-inset-junction-start",
    "row-rule-inset-junction-end"
  ],
  "row-rule-inset-cap": [
    "row-rule-inset-cap-start",
    "row-rule-inset-cap-end"
  ],
  "row-rule-inset-end": [
    "row-rule-inset-cap-end",
    "row-rule-inset-junction-end"
  ],
  "row-rule-inset-junction": [
    "row-rule-inset-junction-start",
    "row-rule-inset-junction-end"
  ],
  "row-rule-inset-start": [
    "row-rule-inset-cap-start",
    "row-rule-inset-junction-start"
  ],
  "rule": [
    "column-rule-width",
    "column-rule-style",
    "column-rule-color",
    "row-rule-width",
    "row-rule-style",
    "row-rule-color"
  ],
  "rule-break": [
    "row-rule-break",
    "column-rule-break"
  ],
  "rule-color": [
    "column-rule-color",
    "row-rule-color"
  ],
  "rule-inset": [
    "row-rule-inset-cap-start",
    "row-rule-inset-cap-end",
    "row-rule-inset-junction-start",
    "row-rule-inset-junction-end",
    "column-rule-inset-cap-start",
    "column-rule-inset-cap-end",
    "column-rule-inset-junction-start",
    "column-rule-inset-junction-end"
  ],
  "rule-inset-cap": [
    "row-rule-inset-cap-start",
    "row-rule-inset-cap-end",
    "column-rule-inset-cap-start",
    "column-rule-inset-cap-end"
  ],
  "rule-inset-end": [
    "column-rule-inset-cap-end",
    "column-rule-inset-junction-end",
    "row-rule-inset-cap-end",
    "row-rule-inset-junction-end"
  ],
  "rule-inset-junction": [
    "row-rule-inset-junction-start",
    "row-rule-inset-junction-end",
    "column-rule-inset-junction-start",
    "column-rule-inset-junction-end"
  ],
  "rule-inset-start": [
    "column-rule-inset-cap-start",
    "column-rule-inset-junction-start",
    "row-rule-inset-cap-start",
    "row-rule-inset-junction-start"
  ],
  "rule-style": [
    "column-rule-style",
    "row-rule-style"
  ],
  "rule-visibility-items": [
    "column-rule-visibility-items",
    "row-rule-visibility-items"
  ],
  "rule-width": [
    "column-rule-width",
    "row-rule-width"
  ],
  "scroll-margin": [
    "scroll-margin-top",
    "scroll-margin-right",
    "scroll-margin-bottom",
    "scroll-margin-left"
  ],
  "scroll-margin-block": [
    "scroll-margin-block-start",
    "scroll-margin-block-end"
  ],
  "scroll-margin-inline": [
    "scroll-margin-inline-start",
    "scroll-margin-inline-end"
  ],
  "scroll-padding": [
    "scroll-padding-top",
    "scroll-padding-right",
    "scroll-padding-bottom",
    "scroll-padding-left"
  ],
  "scroll-padding-block": [
    "scroll-padding-block-start",
    "scroll-padding-block-end"
  ],
  "scroll-padding-inline": [
    "scroll-padding-inline-start",
    "scroll-padding-inline-end"
  ],
  "scroll-timeline": [
    "scroll-timeline-name",
    "scroll-timeline-axis"
  ],
  "text-box": [
    "text-box-trim",
    "text-box-edge"
  ],
  "text-decoration": [
    "text-decoration-line",
    "text-decoration-thickness",
    "text-decoration-style",
    "text-decoration-color"
  ],
  "text-emphasis": [
    "text-emphasis-style",
    "text-emphasis-color"
  ],
  "text-wrap": [
    "text-wrap-mode",
    "text-wrap-style"
  ],
  "timeline-trigger": [
    "timeline-trigger-name",
    "timeline-trigger-source",
    "timeline-trigger-activation-range-start",
    "timeline-trigger-activation-range-end",
    "timeline-trigger-active-range-start",
    "timeline-trigger-active-range-end"
  ],
  "timeline-trigger-activation-range": [
    "timeline-trigger-activation-range-start",
    "timeline-trigger-activation-range-end"
  ],
  "timeline-trigger-active-range": [
    "timeline-trigger-active-range-start",
    "timeline-trigger-active-range-end"
  ],
  "transition": [
    "transition-property",
    "transition-duration",
    "transition-timing-function",
    "transition-delay",
    "transition-behavior"
  ],
  "view-timeline": [
    "view-timeline-name",
    "view-timeline-axis",
    "view-timeline-inset"
  ],
  "white-space": [
    "white-space-collapse",
    "text-wrap-mode"
  ],
  "word-wrap": [
    "overflow-wrap"
  ]
};
